### ISSUE TITLE
请问有实时功能吗

### ISSUE THREAD

**Issue by MikeAiJF** [heifengli001/video-de-clip-moviepy#1]

**Comment by heifengli001** [comment]
这是一个命令行运行的，没有界面，没有实时

**Comment by BigBigDeBoy** [comment]
请问，运行后出现这个错误 ，怎么解决
 File "/Users/dada/video-de-clip-moviepy/index.py", line 195, in <module>
    genrate_video(video_arr,gif_arr)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/dada/video-de-clip-moviepy/index.py", line 128, in genrate_video
    output_index = output_index+1
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'output_index' where it is not associated with a value

**Comment by BigBigDeBoy** [comment]
Traceback (most recent call last):
  File "/Users/dada/video-de-clip-moviepy/index.py", line 197, in <module>
    genrate_video(video_arr,gif_arr)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/dada/video-de-clip-moviepy/index.py", line 132, in genrate_video
    final_clip.write_videofile(os.path.join(output_path, "output"+output_index+".mp4"), codec="libx264", fps=24, threads=4, logger=None,preset='ultrafast')
                                                         ~~~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by BigBigDeBoy** [comment]
Traceback (most recent call last):
  File "/Users/dada/video-de-clip-moviepy/index.py", line 197, in <module>
    genrate_video(video_arr,gif_arr)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/dada/video-de-clip-moviepy/index.py", line 132, in genrate_video
    final_clip.write_videofile(os.path.join(output_path, "output"+output_index+".mp4"), codec="libx264", fps=24, threads=4, logger=None,preset='ultrafast')
                                                         ~~~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by 1083018610** [comment]
> 这是一个命令行运行的，没有界面，没有实时

大神 可以考虑打包成exe吗
